CREATE TABLE USUARIO(
    ID    INT PRIMARY KEY IDENTITY,
    NOME  VARCHAR (100) NOT NULL,
    CPF   CHAR (11)     NOT NULL,
    EMAIL VARCHAR (50)  NOT NULL,
    DATANASCIMENTO  DATE          NOT NULL,
    ATIVO BIT  		NOT NULL			
    
)

SELECT * FROM USUARIO
DROP TABLE USUARIO