CREATE TABLE PRODUTO(
    ID    INT PRIMARY KEY IDENTITY,
    DESCRICAO  VARCHAR (100) NOT NULL,
    PRECO   FLOAT     NOT NULL,
    UNIDADEMEDIDA INT  NOT NULL,
    QTDESTOQUE FLOAT      NOT NULL,
    QTDESTOQUEMINIMO FLOAT      NOT NULL,
    IDCATEGORIA	INT NOT NULL REFERENCES CATEGORIA,
    ATIVO BIT  		NOT NULL			
    
)

SELECT * FROM PRODUTO